### ISSUE TITLE
need information on how to set version information for cli package

### ISSUE THREAD

**Issue by Jimexist** [caicloud/nirvana#118]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

**What you expected to happen**:

need information on how to set version information for cli package

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by ddysher** [comment]
@Jimexist can u be more specific about the requests, whats ur expectation and usage example? BTW, cli package is removed now.

**Comment by Jimexist** [comment]
so this can be closed? @ddysher

**Comment by ddysher** [comment]
SGTM, we can close it.

this is also partially mentioned [here](https://github.com/caicloud/nirvana/issues/51)

/close
