### ISSUE TITLE
Simplify openapi generation process

### ISSUE THREAD

**Issue by ddysher** [caicloud/nirvana#123]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind enhancement

**What happened**:

There is quite a few process when generating openAPI spec.

**What you expected to happen**:

openapi gen should be relatively easy to use.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

/assign @liubog2008 
/priority p1

**Comment by Jimexist** [comment]
also request for generation of graphql schemas

**Comment by kdada** [comment]
Finished in #209. If there are some other questions, please file new issues.
