### ISSUE TITLE
Validation error message is almost impossible to understand

### ISSUE THREAD

**Issue by ddysher** [caicloud/nirvana#126]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind enhancement

**What happened**:

Validation error message is almost impossible to understand, see https://github.com/caicloud/nirvana/pull/120#discussion_r165606919

**What you expected to happen**:

The message should be easy to understand, and precisely locate point of failure.

**How to reproduce it (as minimally and precisely as possible)**:

See this PR: https://github.com/caicloud/nirvana/pull/120

**Anything else we need to know?**:

/assign @walktall 
/priority p1

**Comment by ddysher** [comment]
@walktall please do this for struct validation as well.

**Comment by walktall** [comment]
It does this for struct I think. Check https://github.com/caicloud/nirvana/pull/127/files#diff-87d82f20a24af750cacd8a39e096a337R128
________________________________

**Comment by ddysher** [comment]
oops, i was looking at an older file.
