### ISSUE TITLE
Path item overriding problem in OpenAPI

### ISSUE THREAD

**Issue by liubog2008** [caicloud/nirvana#137]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

/kind bug

**What happened**:
Can't build a nested descriptor

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
I'll fix today(02.05)

A PR related with it #134

**Comment by ddysher** [comment]
@liubog2008 ping
