### ISSUE TITLE
Configuration support, and better startup process

### ISSUE THREAD

**Issue by ddysher** [caicloud/nirvana#139]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind feature

**What happened**:

We need a way for users to handle options in their nirvana apps; on the other hand, we want plugin options and nirvana options to be visible to users via standard cli interface.

A proposed interface:

```go
var o Options

type Options struct {
	skipAuthz bool
}

func main() {
	command := cli.NewNirvanaCommand()
	command.EnablePlugins(&metrics.Options{}, &profiling.Options{})

	command.AddFlag(&cli.BoolFlag{Name: "skip", Destination: &o.skipAuthz})

	if err :=command.Execute(); err != nil {
		log.Fatal(err)
	}
}
```

Here, metrics and profiling plugins are enabled, user should be able to see their options from command line.  Also, nirvana options like ip, port can be seen as well.

User is able to give their options via `AddFlag` call.

**Anything else we need to know?**:

/assign @kdada @zoumo

**Comment by kdada** [comment]
Refer to #159.
