### ISSUE TITLE
better perf tools and metrics

### ISSUE THREAD

**Issue by Jimexist** [caicloud/nirvana#148]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

**What you expected to happen**:

- in README the instructions for `ab` should also include concurrency parameter
- also one should try out `httperf` for another opinion

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by ddysher** [comment]
feel free to make a change :)
