### ISSUE TITLE
add tag "default" for options

### ISSUE THREAD

**Issue by ddysher** [caicloud/nirvana#162]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>

/kind feature

**What happened**:

User provided options can use `desc` tag for description, similarly, we should also provide a `default` tag for them to add flag default.

**Anything else we need to know?**:

Right now, default value is set in config function, i.e.

```go
// Path returns a configurer to set metrics path.
func Path(path string) nirvana.Configurer {
	if path == "" {
		path = "/metrics"
	}
	return func(c *nirvana.Config) error {
		wapper(c, func(c *config) {
			c.path = path
		})
		return nil
	}
}

// Namespace returns a configure to set metrics namespace.
func Namespace(ns string) nirvana.Configurer {
	if ns == "" {
		ns = "nirvana"
	}
	return func(c *nirvana.Config) error {
		wapper(c, func(c *config) {
			c.namespace = ns
		})
		return nil
	}
}
```

What we want is

```go
// Option contains basic configurations of metrics.
type Option struct {
	// Namespace is metrics namespace.
	Namespace string `desc:"Metrics namespace" default:"nirvana"`
	// Path is metrics path.
	Path string `desc:"Metrics path" default:"/metrics"`
}
```

/assign @kdada 
/priority p2

**Comment by kdada** [comment]
This feature is useless.
When a user passes an option to nirvana command, the command can't distinguish if a field should use default value.

**Comment by ddysher** [comment]
As discussed offline, you can distinguish this using pointer value, this is the way Kubernetes deals with default vs no-value.

I'm fine with closing this for now if there is no immediate use case.

**Comment by kdada** [comment]
It may be not suitable with our scene. Fields in `Option` are managed by `pflag`, That means no field can be nil (Of caurse we can write more codes to bypass it). In addition, a pointer field is not easy to use.
e.g.
```
type Option struct {
    Enable *bool
}

// Usage:
enable := true
&Option{
    Enable: &enable,
}
```
