### ISSUE TITLE
Add a OpenAPI endpoint plugin

### ISSUE THREAD

**Issue by liubog2008** [caicloud/nirvana#183]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind feature

**What happened**:

**What you expected to happen**:

A plugin which is easy to register an endpoint to serve OpenAPI documents

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by kdada** [comment]
This issue is expired.
