### ISSUE TITLE
feature request: nirvana log should parse flag

### ISSUE THREAD

**Issue by zjj2wry** [caicloud/nirvana#192]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

 /kind feature

**What happened**:
cc @kdada @ddysher 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by kdada** [comment]
Done by #195
