### ISSUE TITLE
Open Source License Missed

### ISSUE THREAD

**Issue by gaocegege** [caicloud/nirvana#23]
**What is the issue about**:

Open source license

**What happened**:

Missed

**What you expected to happen**:

Add the license to the repository and code.

**Anything else we need to know**:

**Comment by ddysher** [comment]
Thanks!  We'll use Apache, it's being added [here](https://github.com/caicloud/nirvana/pull/25) (I'm requesting a separate PR).

**Comment by zoumo** [comment]
separate to the PR https://github.com/caicloud/nirvana/pull/34

**Comment by ddysher** [comment]
Close via #34  @gaocegege thx!
