### ISSUE TITLE
Add support for golang module function

### ISSUE THREAD

**Issue by MephistoMMM** [caicloud/nirvana#239]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

Now, only configuration files for `dep`  dose nirvana command tool `nirvana` support to generate. But since [version 1.11](https://golang.org/doc/go1.11#modules) , Go has added preliminary support for a new concept called “modules” which will be the official solution of project dependency management.

**What you expected to happen**:

Provide an option for `dep` and  `mod` while user running `nirvana init ./myproject`

**How to reproduce it (as minimally and precisely as possible)**:

modify `nirvana/cmd/nirvana/project/init.go`:

1. add template method for mod file like `templateGopkg` method.
2. register the template. 

**Anything else we need to know?**:

**Comment by kdada** [comment]
Go module is experimental.  My main concern is that it may be changed in the future. 

But it could be an alpha feature of Nirvana!!

If you are interested in this feature and you have times to finish it, you can follow the [CONTRIBUTION.md](https://github.com/caicloud/nirvana/blob/master/CONTRIBUTING.md#write-a-new-feature) and write codes for Nirvana.

**Comment by MephistoMMM** [comment]
I am willing to try. 😄

**Comment by MephistoMMM** [comment]
I defined a boolean flag named `mod`:

```go
	flags.BoolVar(&o.GoMod, "mod", false, "Using golang modules instead of 'dep' (experimental)")
```

And write`exTemplateGopkg` method to generate the path of configuration file and the template function , then replace [key/value](https://github.com/caicloud/nirvana/blob/8678bd29be5fbe536ff0a183567264e5f0e466fd/cmd/nirvana/project/init.go#L229) of `dep` in `templates` method : 

```go
func (o *initOptions) templates(proj string) map[string]string {
	pkgConfPath, templateGopkg := o.exTemplateGopkg()
	return map[string]string{
                ...
		"pkg/version/version.go":                 o.templateVersion(),
		string(pkgConfPath):                      templateGopkg(),
		"Makefile":                               o.templateMakefile(),
                 ...
         }
}
```

Detail of `exTemplateGopkg` : 

```go
func (o *initOptions) exTemplateGopkg() (string, func() string) {
	if o.GoMod {
		return "go.mod", func() string {
			return o.templateGomod()
		}
	}

	return "Gopkg.toml", func() string {
		return o.templateGopkg()
	}
}
```

**Comment by MephistoMMM** [comment]
Also, modify makefile template.

Now it will move packages to `vendor` directory before running docker build command:

```
container:
	@for target in $(TARGETS); do                                                      \
	  for registry in $(REGISTRIES); do                                                \
	    $(shell [ -f go.mod ] && go mod vendor)                                        \
	    image=$(IMAGE_PREFIX)$${target}$(IMAGE_SUFFIX);                                \
	    docker build -t $${registry}$${image}:$(VERSION)                               \
	 ...
```

**Comment by kdada** [comment]
`o.GoMod` looks not very extensible. Adding flag `--vendor` with values `dep`(default) and `mod` is more preferred. 


Why `Makefile` needs to install vendor?

**Comment by MephistoMMM** [comment]
You are right. I will change `--mode` to `--vendor`.

- - - 

The following is from the output of `go help modules` .

> In module-aware mode, GOPATH no longer defines the meaning of imports
during a build, but it still stores downloaded dependencies (in GOPATH/pkg/mod)
and installed commands (in GOPATH/bin, unless GOBIN is set).

If not run command `go mod vendor` ,  go module will download dependencies again while building docker image  , because both `vendor` direactory and `$GOPATH/pkg/mod` direactory are empty.

`go mod vendor` resets the main module's vendor directory to include all packages needed to build.

**Comment by kdada** [comment]
`go mod vendor` only executes once in a build process. So you can let it be a target:

```makefile
mod-vendor:
    do something

container: mod-vendor
    build container
```

The `mod-vendor` is not good. You can give it an appropriate name.
