### ISSUE TITLE
Router regexp match

### ISSUE THREAD

**Issue by walktall** [caicloud/nirvana#24]
**What is the issue about**:

Router regexp

**What happened**:

Given:

```
"/article/{id}/{opts}"
"/article/{iffd}/edit"
```

```
"/files/{id}"
"/files/{id}:delete""
```

Call

```
"/article/111/edit"
```

```
"/files/789:delete"
```

**What you expected to happen**:

Want `iffd:111`

But Got `opts:edit id:111`

Want `id:789`

But Got `id:789:delete`

**Anything else we need to know**:

Tests trigger these can be found in #20 

Cases ported from [here](https://github.com/go-chi/chi/blob/master/tree_test.go)

@kdada @ddysher

**Comment by ddysher** [comment]
Discussed offline during @caicloud/review-framework .   This is work as expected, but we should add notice about this behavior.

**Comment by ddysher** [comment]
@walktall can we close this?
