### ISSUE TITLE
updown file API can not get fileHeader

### ISSUE THREAD

**Issue by zjj2wry** [caicloud/nirvana#249]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind feature

 c.request.FormFile(key) should return fileHeader, because fileHeader have content and filename. but file only have content

```
// File returns a file reader when "Content-Type" is "multipart/form-data".
func (c *container) File(key string) (multipart.File, bool) {
	file, _, err := c.request.FormFile(key)
	return file, err == nil
}
```
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by kdada** [comment]
You can bypass it through extracting request from context directly.

If you think the API has weak adaptability, Please consider about implementing a stronger interface to replace `multipart.File`.

**Comment by zjj2wry** [comment]
> If you think the API has weak adaptability, Please consider about implementing a stronger interface to replace multipart.File.

make sense，but i think it would be better have a mechanism for definition to pass multiple key values. Or let the user customize the definition.

**Comment by kdada** [comment]
For APIs, users don't need to know how to get data from http requests. They should only care about business logic.

An example with RESTful style:
```
API: POST /files?name=xxx
Function: func CreateFile(name string, data io.ReadCloser) (SomeObject, error)
``` 
Of course, sometimes APIs need to adapt to strange demands. So you can got meta from http request directly. But for convenient, we can extends `File(key string) (multipart.File, bool)` to:
```go
type File interface {
    miltipart.File
    Header() *multipart.FileHeader
}

File(key string) (File, bool)
```
Then users can define their APIs like:
```go
Function: func CreateFile(name string, data service.File) (SomeObject, error)
```

**Comment by zjj2wry** [comment]
i think it would be better define ```type CustomFile interface``` in user own project instead of nirvana project. Can we set a custom definition? Such as definition.CustomFile

**Comment by kdada** [comment]
Actually, users can implement a new interface which is a subset of `service.File`. For example:
```go
type MyFile interface {
    io.ReadCloser
    Header() *multipart.FileHeader
}

func CreateFile(name string, data MyFile) (SomeObject, error)
```

Nirvana supports it.
