### ISSUE TITLE
how can i get execute error？

### ISSUE THREAD

**Issue by zjj2wry** [caicloud/nirvana#251]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind feature

**What happened**:
```golang
func (s *service) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	for _, f := range s.filters {
		if !f(resp, req) {
			return
		}
	}
	ctx := newHTTPContext(resp, req)

	executor, err := s.root.Match(ctx, &ctx.container, req.URL.Path)
	if err != nil {
		if err := writeError(ctx, s.producers, err); err != nil {
			s.logger.Error(err)
		}
		return
	}
	err = executor.Execute(ctx)
	if err == nil && ctx.response.HeaderWritable() {
		err = invalidService.Error()
	}
	if err != nil {
		if ctx.response.HeaderWritable() {
			if err := writeError(ctx, s.producers, err); err != nil {
				s.logger.Error(err)
			}
		} else {
			s.logger.Error(err)
		}
	}
}
```

```err = executor.Execute(ctx)```can we set this err into context, then we get this err in my middleware. because i want process my common error in last middleware.

## example
origin:
```golang
Function: func(ctx context.Context, partition string) (*project.ProjectList, error) {
		return project.List(partition)
	}
```

now : because i need convert apiserver error to nirvana
```golang
Function: func(ctx context.Context, partition string) (*project.ProjectList, error) {
		pList, err := project.List(partition)
		if err != nil {
			return nil, errors.APIServerErrorToNirvanaError(err)
		}
		return pList, 
	}
```

/cc @kdada 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by zjj2wry** [comment]
got it，thanks

will attemp use Operator convert my API handle result.

**Comment by zjj2wry** [comment]
Do we have an example to use Operator in Definition.Results?

**Comment by kdada** [comment]
It's totally same as `Parameter.Operator`. Example: https://github.com/caicloud/nirvana/blob/master/examples/api-basic/api/v1/app.go
