### ISSUE TITLE
[problem] Fail to run the test command in Makefile

### ISSUE THREAD

**Issue by gaocegege** [caicloud/nirvana#252]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

When I run `make`, code [here](https://github.com/caicloud/nirvana/blob/master/cmd/nirvana/project/init.go#L747) output an error to STDERR:

```
/bin/sh: 1: [[: not found
```

**What you expected to happen**:

Generate v-dirty if there are changes, generate v if there is no change.

**How to reproduce it (as minimally and precisely as possible)**:

```bash
nirvana init ./myproject
cd ./myproject
make
```

## Solution

```
COMMIT := $(COMMIT)$(shell git diff-files --quiet || echo '-dirty')
```

**Comment by kdada** [comment]
Please test it in MacOS and Linux.

**Comment by gaocegege** [comment]
I have no macOS machine now. The problem can be reproduced in Linux (4.4.0-78-generic).

**Comment by caitong93** [comment]
I test this on Mac, CentOS and Ubuntu. Only reproduced this on Ubuntu.

**Comment by caitong93** [comment]
I think this is caused by difference of `sh` and `bash`. 
On CentOS and Mac, `/bin/sh`(or /usr/bin/sh) is a symbol link to `bash`.

**Comment by kdada** [comment]
@gaocegege please file a PR to fix it.
