### ISSUE TITLE
什么时候可以支持mod?

### ISSUE THREAD

**Issue by binfer** [caicloud/nirvana#262]
什么时候可以支持mod?

**Comment by liubog2008** [comment]
https://github.com/caicloud/nirvana/issues/239

@kdada 支持了吧？

**Comment by kdada** [comment]
It's already being supported.

```go
nirvana init --package-manager=mod
```

I'll close this issue because it's done. If you have any other questions, feel free to reopen this issue.

**Comment by hxdhero** [comment]
--package-manager
v0.2 没有这个参数?

**Comment by ddysher** [comment]
/reopen

需要一个 release

**Comment by kdada** [comment]
@hxdhero Please use master now. we'll release v0.2.1 after merging #263

**Comment by hxdhero** [comment]
@kdada ok
