### ISSUE TITLE
Generated api json file has only one line

### ISSUE THREAD

**Issue by supereagle** [caicloud/nirvana#265]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

The generated api json file has only one line, which is very hard to read.

**What you expected to happen**:

The generated api json file has readable format.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by kdada** [comment]
Will you modify the file manually?

**Comment by supereagle** [comment]
I will not modify it, but will likely read it.
