### ISSUE TITLE
Can not generate api docs for AutoParameter when business function argument is pointer

### ISSUE THREAD

**Issue by wutzx** [caicloud/nirvana#268]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Can not generate api docs for AutoParameter when bussiness function argument is pointer

**What you expected to happen**:

Can generate api docs for AutoParameter when bussiness function argument is pointer

**How to reproduce it (as minimally and precisely as possible)**:

Define auto parameter as pointer in business function argument, example:

```go
type MessageOption struct {
	// Example is test auto option.
	Example string `source:"Query,example"`
}

func GetMessage(ctx context.Context, id int, option *MessageOption) (*Message, error) {
    ...
}
```

**Anything else we need to know?**:

Nothing

**Comment by kdada** [comment]
are you interested in fixing this problem? If not, I'll fix this issue later.
