### ISSUE TITLE
Support 405, 406, 415

### ISSUE THREAD

**Issue by ddysher** [caicloud/nirvana#28]
**What is the issue about**:

Methods support in Framework.

**What happened**:

nirvana doesn't support following methods right now:
- 405 Method Not Allowed
- 406 Not Acceptable
- 415 Unsupported Media Type

**What you expected to happen**:

All commonly used method should be supported

**Anything else we need to know**:

@caicloud/review-framework who wanna take this?

**Comment by Jimexist** [comment]
Personally I like [418](https://httpstatuses.com/418)

**Comment by kdada** [comment]
It's supported now.

**Comment by ddysher** [comment]
@kdada are u working on this?  I'm thinking of assigning to someone else to get them familiar with the framework.

@caicloud/review-framework

**Comment by kdada** [comment]
@ddysher  ok.

**Comment by kdada** [comment]
It's supported now.
