### ISSUE TITLE
Sync the template content in nirvana init with nirvana-template-project repo

### ISSUE THREAD

**Issue by iawia002** [caicloud/nirvana#304]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind feature

Since we have the [nirvana-template-project](https://github.com/caicloud/nirvana-template-project) repo, maybe we should sync the template content in nirvana init command with nirvana-template-project repo, and then deprecate nirvana-template-project repo, all nirvana projects can be easily generated by `nirvana init xxx`.

And since almost all projects have migrated to go mod, maybe we can also drop support for generating project with dep as a package manager, just go mod.

/cc @supereagle @hezhizhen

**Comment by hezhizhen** [comment]
SGTM

**Comment by supereagle** [comment]
> then deprecate nirvana-template-project repo, all nirvana projects can be easily generated by `nirvana init xxx`

Maybe not all of nirvana-template-project can be covered by `nirvana init xx`, like Dockerfile and Makefile. 

> And since almost all projects have migrated to go mod, maybe we can also drop support for generating project with dep as a package manager, just go mod.

LGTM
