### ISSUE TITLE
【API-DOC】2 warning in generated API document

### ISSUE THREAD

**Issue by tskdsb** [caicloud/nirvana#330]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:
![image](https://user-images.githubusercontent.com/11919928/82427911-517e9200-9abc-11ea-9ddf-5213b318df25.png)

- missingProperty: description
- additionalProperty: title

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by iawia002** [comment]
> missingProperty: description

This is actually you did not fill in the description in `Definition.Results`. eg: `Results: def.DataErrorResults(""),`

> additionalProperty: title

I'll take a look at this.
