### ISSUE TITLE
failed to generate nirvana client 

### ISSUE THREAD

**Issue by moshuipan** [caicloud/nirvana#349]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
when definition.Function have a receiver, the generated function name will end with `-fm` (is append by `runtime.FuncForPC`),
```go
type handler struct {}
func (h handler) Create(ctx contex.Contex) error{}
```
got error:
```bash
ERROR 0728-15:37:51.254+08 generator.go:84 | 17:13: expected ';', found '-' (and 2 more errors)
FATAL 0728-15:37:51.254+08 client.go:44 | 17:13: expected ';', found '-' (and 2 more errors)
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by iawia002** [comment]
You can control the generated function name by add `Summary` field of the `Definition`, eg:

```
def.Definition{
	Method:      def.List,
	Summary:     "Summary Name",
	Description: "Query a specified number of messages and returns an array",
	Function:    storagev1a1.ListMessages,
	...
}
```

the output generated function name will be `SummaryName`, try if this can solve your problem.
