### ISSUE TITLE
GitHub page and example projects

### ISSUE THREAD

**Issue by Jimexist** [caicloud/nirvana#39]
**What is the issue about**:
GitHub pages should be set up along with two example projects:
- hello world
- todo app

**What happened**:
Nothing happened, I just figure that a more out-reaching stance this repo shall take.

**What you expected to happen**:
More open source usage, more tractions, etc.

**Anything else we need to know**:

- [x] skeleton #40 
- [ ] add status badge and add *fork me at github button* 
- [ ] choose a better theme
- [x] create `CNAME` and apply domain

**Comment by ddysher** [comment]
nice!  Apart from examples, we also need to add more documentation, usage, etc.

Do you need a domain :)  http://gonirvana.org/ ?

**Comment by ddysher** [comment]
As discussed offline, apart from a 'large' getting started example, we need a set of small example projects to demonstrate features. Below is a non-exhaustive list:

- [ ] hello-world example
- [ ] stream API
- [ ] error message
- [ ] openapi generation
- [ ] cli configuration
- [ ] tracing

@kdada to add more
