### ISSUE TITLE
request for some built-in routes

### ISSUE THREAD

**Issue by Jimexist** [caicloud/nirvana#51]
request for some built-in routes:

e.g. 
- [ ] a helper to expose a `/version` route that can contain
  - version info e.g. git tag or `sha` digest
  - application name
  - other useful, public, non-security related info that'll help to identify the version
- [x] a helper to define metrics (e.g. hook up with Promethus) at `/metrics`
- [ ] a ping method for load balance health check at `/ping`?

**Comment by ddysher** [comment]
@kdada to triage

**Comment by ddysher** [comment]
feel free to reassign

**Comment by ddysher** [comment]
@kdada needs your input

**Comment by kdada** [comment]
I'll mark it in refactor doc.
