### ISSUE TITLE
validator error format refine

### ISSUE THREAD

**Issue by walktall** [caicloud/nirvana#52]
**What is the issue about**:

Validator should have a refined error format.

**What happened**:

Currently, error returned from validator.v9 is not clearly enough.

**What you expected to happen**:

A well formatted error for nirvana.

**Anything else we need to know**:

**Comment by ddysher** [comment]
Can you give an example of what works and whatnot?  It seem they do [process errors](https://github.com/go-playground/validator/blob/e3037695c7ae7262d462bbd8698f621ca768d128/errors.go).

**Comment by ddysher** [comment]
@walktall ping

**Comment by walktall** [comment]
duplicate with #126
