### ISSUE TITLE
better construction for flags

### ISSUE THREAD

**Issue by Jimexist** [caicloud/nirvana#58]
**What is the issue about**:
Improvement needed for StringFlag

<img width="289" alt="screenshot 2017-12-13 17 49 17" src="https://user-images.githubusercontent.com/622789/33932513-155155b0-e02e-11e7-912d-e16062bf4c21.png">

**What happened**:
There are simply too many fields to be filled for StringFlag.

**What you expected to happen**:
Should be a builder or some other helper functions to fulfill default values.

**Anything else we need to know**:

**Comment by ddysher** [comment]
Can you just leave the flag field empty?

**Comment by zoumo** [comment]
+1, leave the fields empty.
Only `Name` is required, the others are optional.

**Comment by Jimexist** [comment]
no action
