### ISSUE TITLE
validator error is unreadable

### ISSUE THREAD

**Issue by Jimexist** [caicloud/nirvana#74]
**What is the issue about**:
While using validator, the error message is unreadable

**What happened**:

While using validator:
```
Operators: []definition.Operator{
							validator.Var("gte=0"),
						},
```

the error message is:
```
[query]first: Key: '' Error:Field validation for '' failed on the 'gte' tag
```

**What you expected to happen**:

**Anything else we need to know**:

**Comment by walktall** [comment]
duplicated with https://github.com/caicloud/nirvana/issues/52
