### ISSUE TITLE
application/json 4xx error when Accept is supplied

### ISSUE THREAD

**Issue by Jimexist** [caicloud/nirvana#75]
**What is the issue about**:
4xx error should be in json format if `Accept: application/json` header is specified

**What happened**:
For now only `text/plain` is returned

**What you expected to happen**:

**Anything else we need to know**:

**Comment by kdada** [comment]
Now all errors are formatted to the type defined in `Accept`. If `Accept` is not acceptable, defaults to `application/json`.
