### ISSUE TITLE
Proposal for refactoring nirvana

### ISSUE THREAD

**Issue by kdada** [caicloud/nirvana#83]
## Why to refactor the framework

1. We don't have a consistent design goal.
  - A framework package should not expose methods/functions which is from other packages.
  - A framework package provides interfaces to plug other packages rather than depend on those packages derectly. 
  - Main packages of nirvana should reduce dependencies with other packages (promote interface).
2. We don't have a consistent code style.
  - Replace `SOME_CONST` with `SomeConst`.
  - Hide unused vars and functions. #15
3. Package paths is chaotic.
4. Some packages contain limitations/bugs.
  - `Match` mehtod in router should support returning error. #28 #72
  - Helper functions for `/version`, `/metrics`, `/ping`. #51
  - Use `nirvana/errors` instead of go `errors` and refine error messages. #52 #59 #75
  - More validations. #60 
  - More middlewares. #62
  - More debug info. #63
  - Make `definition.Operator` to be an interface. #68

**The most important Goal: Users only need to import packages which they used.**

## Target directory tree
```
.
├── cli
├── cmd
│   ├── openapi-gen
│   ├── client-gen
│   └── nirvana
├── definition
├── docs
│   └── gitbook
├── errors
├── examples
│   ├── api-basic
│   ├── cli
│   └── stream
├── hack
│   ├── flag-gen
│   ├── license
│   └── boilerplate
├── log
├── middlewares
│   └── tracing
├── operators
│   └── validator
├── service
│   └── router
├── utils
│   ├── metrics
│   ├── probe
│   ├── profiling
│   └── version
│   └── openapi
└── nirvana.go
```
#### Framework Core Packages
- `definition`: The package provides a self-described structure to define RESTful APIs.
- `errors`: The package defines a structured error for users to create reasonable errors.
- `log`: The package provides a glog style interface to output runtime info.
- `service`: The package transforms definitions to http routers and executors (from `web`).
  - `router`: The package provides a general-purpose router to match executors for paths.

##### Dependency Graph
```
                       -----------
                       | service | 
                       -----------
       ---------------------|--------------------
       |                |           |           |
--------------    ----------    -------    ----------
| definition |    | router |    | log |    | errors |
--------------    ----------    -------    ----------
```

#### Framework Core Tools
- `cli`: The package contains many utils to create commands.
- `cmd`: The package contains commands to generate project-related codes.
  - `openapi-gen`: The command generates openapi document from definitions.
  - `client-gen`: The command generates go client by definitions.
  - `nirvana`: The command generates standard project structure (`openapi-gen` and `client-gen` could be merged into this command).
- `middlewares`: The package contains all middlewares.
  - `tracing`: The package implements a middleware for opentracing.
- `operators`: The package contains operators for handling API fields.
  - `validator`: The package provides a bundle of validators to validate request fields.
- `utils`: The package contains many utils to help users to implement some functionalities quickly.
  - `metrics`: The util provides prometheus support.
  - `probe`: The util provides health check.
  - `profiling`: The util provides golang profiling.
  - `version`: The util provides http handler for application version.
  - `openapi`: The util provides functionalities for serving openapi pages.
- `nirvana`: The package is the root package of nirvana. It provides configurations to install utils and can run a server for application.

##### Dependency Graph
```
                          -------
                          | cli | 
                          -------
       ----------------------|-------------------
       |                |                       |
-----------    --------------------    ---------------------
| spf13/* |    | stretchr/testify |    | fsnotify/fsnotify |
-----------    --------------------    ---------------------

                               -----------------
                               | middlewares/* | 
                               -----------------
       --------------------------------|-------------------------
       |                               |                        |
----------------------    ----------------------------    -------------
| nirvana/definition |    | prometheus/client_golang |    | others... |
----------------------    ----------------------------    -------------

                                ---------------
                                | operators/* | 
                                ---------------
       --------------------------------|------------------------
       |                               |                       |
----------------------    ---------------------------    -------------
| nirvana/definition |    | go-playground/validator |    | others... |
----------------------    ---------------------------    -------------

          -----------
          | utils/* | 
          -----------
       --------|-------
       |              |        
-----------    -------------
| nirvana |    | others... |
-----------    -------------
```

#### Framework Chores
- `docs`: The package contains document for nirvana.
- `examples`: The package provides many examples to explain how to use nirvana.
- `hack`: The package contains some tools to maintain nirvana.

## Plan
1. Adjust directory structure.
2. Refactor `nirvana/log` and `nirvana/errors`.
  - Implement a simple logger in `nirvana/log`.
  - Refine `nirvana/errors`.

👆 第一波
<hr />
👇 第二波

3. Refactor `nirvana/service/router`.
  - Add errors in `nirvana/service/router`.
4. Refactor `nirvana/definition` and `nirvana/service`.
  - Enrich `nirvana/definition`.
  - Optimize `nirvana/service`.
5. Refator `middlewares/*` and `operators/*`.
  - Implement `nirvana/definition.Middleware`s.
  - Implement `nirvana/definition.Operator`s.
6. Implement `nirvana` with plugin mode.
  - Implement `nirvana` configurations.
  - Implement `nirvana` server.
7. Refactor and implement `utils`.
8. Refactor `cli`.
  - Remove functions which expose from `cobra` and `viper` directly.
9. Refactor `cmd`.
10. Refine `docs`, `examples`, `hack`.

**Comment by kdada** [comment]
@caicloud/review-framework

**Comment by Jimexist** [comment]
I think this PR is too far-fetching, including many things need to be in separate PRs. don't try to do everything in one PR.

e.g. 
> Replace SOME_CONST with SomeConst.

can be enforced by adding linters in `gomentalinter` in travis-ci

**Comment by zoumo** [comment]
> nirvana: The package is the root package of nirvana. The package provides configurations to install utils. The packages can run a server for application.

It looks very strange to place a `nirvana` dir in `nirvana` project.
If so, we need to import like that
```go
import github.com/caicloud/nirvana/nirvana
```
but I only want to import 
```go
import github.com/caicloud/nirvana
```

**Comment by ddysher** [comment]
@zoumo I believe by nirvana package, @kdada means the top level package, not another nested nirvana package

**Comment by kdada** [comment]
@Jimexist Some PRs have been merged. Those code should be modified in this refactor.

**Comment by Jimexist** [comment]
for code styles you can see https://github.com/caicloud/nirvana/pull/88 - it should fix many problems and forbid more to come

**Comment by Jimexist** [comment]
```sh
goimports -w ./...
```

**Comment by Jimexist** [comment]
@kdada can u update? what is the status now?

**Comment by kdada** [comment]
@Jimexist I'm refactor `router` now. It makes many changes.

**Comment by kdada** [comment]
PR has merged.
