### ISSUE TITLE
Simplify errors package

### ISSUE THREAD

**Issue by Jimexist** [caicloud/nirvana#84]
Currently the `errors` package is a bit cumbersome:

```go
errors.NotFound.NewFactory("not found", "").New("")
```

in order to make a simple not found error.

Suggest to use shortcuts or simply API structure.

**Comment by zoumo** [comment]
There should be some built-in factory to help end users to `New` common erros
```go
errors.NotFoundFactory.New()
// or
errors.NotFoundError
```

**Comment by kdada** [comment]
Now we can use:
```
errors.BadRequest.Error("application ${name} is too short", appName)
```
It still uses the format `${var}` instead of `%s`. Because the former is more clear in format sentence.
