### ISSUE TITLE
Swapi example project

### ISSUE THREAD

**Issue by Jimexist** [caicloud/nirvana#85]
## Deadline

Dec 31 2017

## Checklist

- [x] [cli setup](https://github.com/caicloud/nirvana/pull/49)
- [x] [list example](https://github.com/caicloud/nirvana/pull/80)
- [ ] validation example
- [ ] logging example
- [ ] errors handling example 
- [ ] documentation & write up

_Notice that there's no tracing example_

**Comment by Jimexist** [comment]
update: i am thinking of abandoning this example and instead write https://github.com/caicloud/nirvana_example_meeting_rooms/

**Comment by ddysher** [comment]
@Jimexist Do you want to close this?

/lifecycle freeze
