### ISSUE TITLE
Specify the owner of the copyright in LICENSE

### ISSUE THREAD

**Issue by gaocegege** [caicloud/nirvana#96]
https://github.com/caicloud/nirvana/blob/master/LICENSE#L190

**Comment by kdada** [comment]
>The Apache 2.0 license includes an Appendix about how to apply the license terms to files. We should not modify the license file and instead should tell people what to do as far as dates, etc in the devel guides.

Same as https://github.com/kubernetes/kubernetes-template-project/issues/3
